weatherapi:
  api-key: "su-api-key-de-weatherapi"
  base-url: "https://api.weatherapi.com/v1"
  location: "CABA"

spring:
  datasource:
    url: "jdbc:h2:file:./data/climalertdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: "smtp-relay.brevo.com"
    port: 587
    username: "su-usuario-smtp"
    password: "su-password-smtp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

climalert:
  destinatarios: "email1@ejemplo.com,email2@ejemplo.com"
