# WeatherAPI
weatherapi.api-key=eff73b7f97c0434a80133339260707
weatherapi.base-url=https://api.weatherapi.com/v1
weatherapi.location=CABA

# H2 Database (en memoria)
spring.datasource.url=jdbc:h2:mem:climalertdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Mail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_EMAIL@gmail.com
spring.mail.password=TU_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Destinatarios de alertas
climalert.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com
